# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[workspace]
members = ["crates/opentalk-nextcloud-client"]
resolver = "2"

[workspace.package]
authors = ["OpenTalk Team <mail@opentalk.eu>"]
edition = "2021"
homepage = "https://opentalk.eu/"
license = "EUPL-1.2"
repository = "https://git.opentalk.dev/opentalk/backend/libs/opentalk-shared-folder"

[workspace.dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive", "env"] }
derive_more = { version = "2.0", features = [
  "as_ref",
  "display",
  "from",
  "from_str",
  "into",
] }
log = "0.4"
reqwest = { version = "0.13", features = ["json"] }
reqwest_dav = "0.3.0"
serde = { version = "1", features = ["derive"] }
snafu = "0.9"
strum = { version = "0.28", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
url = "2"
