version = 1
SPDX-PackageName = "OpenTalk NextCloud Client"
SPDX-PackageSupplier = "OpenTalk GmbH <mail@opentalk.eu>"
SPDX-PackageDownloadLocation = "https://git.opentalk.dev/opentalk/backend/libs/opentalk-nextcloud-client"

[[annotations]]
path = ["Cargo.lock", "README.md", "renovate.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "OpenTalk GmbH <mail@opentalk.eu>"
SPDX-License-Identifier = "EUPL-1.2"
